config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'tasks#dashboard'
  resources :tasks

  post '/update-task-status' => "tasks#update_task_status", as: :update_status
  
  get '/update-all-task-status' => "tasks#all_status_update"

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	validates :title, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :authenticate_user!

	def dashboard
	end

	def create
		current_user.tasks.create(title: params[:title])
		redirect_to root_path
	end

	def update_task_status
		Task.find(params[:id].to_i).toggle! :finished
		redirect_to root_path
	end

	def all_status_update
		current_user.tasks.update_all(finished: true)
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/dashboard.html.erb
<br/><br/><br/><br/><br/><br/>
<div class="row col-md-offset-3 col-sm-offset-1 col-xs-offset-1">
	<div class="col-md-7 col-sm-11 col-xs-11 task-panel">

		<div class="row">
			<a href="/update-all-task-status" class="pull-right">Mark all as finished <i class="fa fa-check-circle"></i></a>
		</div>

		<hr/>

		<div class="row">
			<h3>Things I need to do...</h3>
		</div>

		<div class="row">
			<br/>

			<ul class="tasks-list">
				<% current_user.tasks.each_with_index do |task,index| %>
				<div class="col-md-6 col-sm-12 <%= 'task_complete' if task.finished %>">

				<% if index.even? %>
					<li> 
				<% else %>
					<li class="odd-task"> 
				<% end %>

						<%= task.title %>

						<%= form_tag update_status_path, :id => 'form'+task.id.to_s do %> 
							<%= hidden_field_tag :id, task.id %>
							<a href="#" class="pull-right check-icon" data-id="<%=task.id%>">
								<i class="fa <%= task.finished ? 'fa-check-circle' : 'fa-check-circle-o'%>"></i>
							</a>
						<% end %>

					</li>
				</div>
				<% end %>
			</ul>

			<br/>
		</div>

		<div class="row">
			<br/>
			<h4> Things I should do next ....  
				<a data-toggle="modal" href="#taskModal">
					<i class="fa fa-plus-square-o add-button pull-right"></i>
				</a>
			</h4>
		</div>

</div>

<div id="taskModal" class="modal fade in">
  <div class="modal-dialog">
      <div class="modal-content">

      	<%= form_for Task.new do %>
          <div class="modal-header">
              <h4 class="modal-title">Add a Task</h4>
          </div>
          <div class="modal-body">
            <%= text_field_tag :title, nil, class: "form-control" %>
          </div>
          <div class="modal-footer">
            <button class="btn btn-primary"> Add </button>
          </div>
        <% end %>

      </div>
  </div>
</div>